aws_region            = "us-east-1"
project_name          = "rr-djuikoo.com"
site_bucket_name      = "rr-djuikoo-site"
artifact_bucket_name  = "rr-djuikoo-lambda-artifacts"
sessions_table_name   = "rr-djuikoo-sessions"
rate_limit_table_name = "rr-djuikoo-chat-rate-limit"
