#!/usr/bin/env node
// Renders the portfolio content into the two artefacts that get deployed:
//
//   src/profile.mjs  ->  site/index.html    (browsers and crawlers)
//                    ->  site/content.json  (read from S3 by agent/content.mjs)
//
// Both outputs are committed. Run `make build` after editing src/profile.mjs;
// the build-site pre-commit hook fails if they drift out of sync.
//
// The template language has exactly two directives:
//
//   {{ dotted.path }}                   escaped interpolation, resolved against
//                                       the current scope then the root object
//   <template data-each="path">...      repeats its body once per array item,
//   </template>                         each item becoming the current scope;
//                                       {{ . }} is a scalar item
//
// <template> is used as the loop marker because the tag cannot appear in text
// content, so depth counting is enough to find its match - no HTML parser.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import profile from "../src/profile.mjs";

const root = new URL("..", import.meta.url);
const TEMPLATE_FILE = fileURLToPath(new URL("src/index.template.html", root));
const HTML_OUT = fileURLToPath(new URL("site/index.html", root));
const JSON_OUT = fileURLToPath(new URL("site/content.json", root));

const BANNER =
  "<!-- Generated by scripts/build-site.mjs from src/profile.mjs — do not edit manually -->";

const HTML_ESCAPES = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
const PLACEHOLDER = /\{\{\s*([^}\s]+)\s*\}\}/g;
// Inline emphasis, applied *after* escaping: by then every "<" is already
// "&lt;", so <strong> and <em> are the only tags this generator can emit.
// Consequence: never use an asterisk outside prose - in an attribute it would
// produce broken markup.
const BOLD = /\*\*([^*]+)\*\*/g;
const ITALIC = /\*([^*]+)\*/g;
const TEMPLATE_OPEN = /<template\b[^>]*\bdata-each="([^"]+)"[^>]*>/;
// Authoring notes: kept in the template, stripped from the published page.
const TODO_LINE = /^[ \t]*<!--\s*TODO\(content\)[^\n]*?-->[ \t]*\r?\n/gm;
const TODO_INLINE = /<!--\s*TODO\(content\)[\s\S]*?-->/g;
// Indentation left over once a tag that sat alone on its line is removed.
const DANGLING_INDENT = /(^|\n)[ \t]+$/;

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => HTML_ESCAPES[char]);
}

function emphasize(text) {
  return text.replace(BOLD, "<strong>$1</strong>").replace(ITALIC, "<em>$1</em>");
}

function resolvePath(path, scope, rootScope) {
  if (path === ".") return scope;

  for (const source of [scope, rootScope]) {
    let current = source;
    let found = true;

    for (const key of path.split(".")) {
      if (current === null || typeof current !== "object" || !(key in current)) {
        found = false;
        break;
      }
      current = current[key];
    }

    if (found) return current;
  }

  throw new Error(`Unknown template path: {{ ${path} }}`);
}

function interpolate(html, scope, rootScope) {
  return html.replace(PLACEHOLDER, (_, path) => {
    const value = resolvePath(path, scope, rootScope);
    if (value === undefined || value === null) {
      throw new Error(`Template path {{ ${path} }} resolved to ${value}`);
    }
    return emphasize(escapeHtml(value));
  });
}

// Returns the body of the <template> block opened before `start`, plus the
// offset just past its matching close tag.
function readTemplateBody(html, start) {
  const token = /<\/?template\b/g;
  token.lastIndex = start;
  let depth = 1;
  let match;

  while ((match = token.exec(html)) !== null) {
    if (match[0] !== "</template") {
      depth += 1;
      continue;
    }

    depth -= 1;
    if (depth > 0) continue;

    const body = html.slice(start, match.index).replace(DANGLING_INDENT, "$1");
    let end = html.indexOf(">", match.index) + 1;
    if (html[end] === "\n") end += 1;
    return { body, end };
  }

  throw new Error("Unclosed <template data-each> block");
}

function render(html, scope, rootScope) {
  let out = "";
  let rest = html;

  for (;;) {
    const match = TEMPLATE_OPEN.exec(rest);
    if (!match) {
      out += interpolate(rest, scope, rootScope);
      break;
    }

    out += interpolate(rest.slice(0, match.index).replace(DANGLING_INDENT, "$1"), scope, rootScope);

    let bodyStart = match.index + match[0].length;
    if (rest[bodyStart] === "\n") bodyStart += 1;

    const { body, end } = readTemplateBody(rest, bodyStart);
    const items = resolvePath(match[1], scope, rootScope);
    if (!Array.isArray(items)) {
      throw new Error(`data-each="${match[1]}" does not point to an array`);
    }

    for (const item of items) out += render(body, item, rootScope);
    rest = rest.slice(end);
  }

  return out;
}

// No trailing whitespace and exactly one final newline, so the trailing-whitespace
// and end-of-file-fixer hooks never rewrite what this script just produced.
function normalize(text) {
  return `${text
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n")
    .replace(/\n+$/, "")}\n`;
}

const template = readFileSync(TEMPLATE_FILE, "utf8")
  .replace(TODO_LINE, "")
  .replace(TODO_INLINE, "");

const html = render(template, profile, profile).replace(
  /^<!DOCTYPE html>\n/,
  `<!DOCTYPE html>\n${BANNER}\n`
);

writeFileSync(HTML_OUT, normalize(html));
writeFileSync(JSON_OUT, `${JSON.stringify(profile, null, 2)}\n`);

console.log(`site/index.html   ${normalize(html).length} octets`);
console.log(`site/content.json ${JSON.stringify(profile, null, 2).length + 1} octets`);
